### PR TITLE
Update package dependencies

### PR DESCRIPTION
**Pull request by SathwikPanchangam**
## Changelog

* Add dependencies in `mdr_find_object_action`.
* Add dependecies in `mdr_rosplan_interface`.

## Checklist:
- [x] My code doesn't contain unnecessary comment blocks (e.g. unused code, templates of `package.xml` or `CMakeLists.txt`)
- [x] I have updated the `package.xml` and `CMakeLists.txt` with the correct dependencies.

### CODE REVIEW

**Comment by minhnh** [comment]
@SathwikSai10 please add some description for the changes in `move_base_action_client_test`

**Review by alex-mitrevski — CHANGES_REQUESTED** [review]
I'm OK with the changes, except for the added `requirements.txt` file; there is no point in adding it to this specific package since other packages have those dependencies as well.

**Comment by minhnh** [comment]
I think it should be noted somewhere if the successful execution of the main launch file requires these packages. Maybe `README.md` is a better place?

**Comment by minhnh** [comment]
@alex-mitrevski or perhaps a `requirements.txt` for the whole repository? Though only `pymongo` is explicitly used in `mdr_rosplan_interface` I think, the other dependencies are probably in some other repositories (actually both are from `mas_knowledge_base` now that I take a look).

**Review by minhnh — CHANGES_REQUESTED** [review]
@SathwikSai10 could you [squash the previous commits into one](https://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git)? I think only the last commit makes sense for this PR.

**Comment by argenos** [comment]
> perhaps a `requirements.txt` for the whole repository?

Ideally, no requirements.txt at all would be used. Are these packages not available through rosdep? I'm planning on adding the CI again, and I'd rather this is handled automatically with known ROS dependencies than us manually maintaining the requirements.txt file.

**Comment by minhnh** [comment]
How does it work for packages installed with `pip`? I saw that `python3-termcolor` and `python3-rdflib` do exist, so we can maybe add them to `package.xml` of `mas_knowledge_base`. `python3-rdflib` is quite old though, not sure if that'd be an issue.

**Review by minhnh — APPROVED** [review]

**Pull request merged**
