### PR TITLE
Refactor/perception/remove segmentation dependency

### PR DESCRIPTION
**Pull request by minhnh**

### CODE REVIEW

**Comment by sthoduka** [comment]
I am not in favour of this. We use bounding_box code (for example) in mas_industrial as well, hence it should be part of the common code

**Comment by alex-mitrevski** [comment]
I agree that `mdr_perception_libs` as a whole could eventually become a separate repository that could be used in general, but this is still under development and the current API is only used in this repository, so at least for the time being, this has to stay here.

**Comment by argenos** [comment]
I think mas_perception needs a lot of refactoring, perhaps we can consider moving it once it’s ready and we are done refactoring what’s in there

**Comment by alex-mitrevski** [comment]
Agreed; that's exactly what @minhnh and I were just discussing.

**Pull request merged**
