### PR TITLE
Implementing a ros wrapper for rasa

### PR DESCRIPTION
**Pull request by henrikschnor**
This is a first prototype of a ros wrapper for rasa nlu. See issue #84. It gets messages from an input topic, runs them through rasa and outputs the results to another topic. A second ros-node is provided that can be used for training models.

### CODE REVIEW

**Comment by henrikschnor** [comment]
Things I'm unsure about:

- At the moment I'm using rasa's python API. A perhaps better option could be to run rasa (with all it's dependencies) in a docker container and interact using the http API
- Which topics should we use for input/output? We could use the input directly from /speech_recognizer, but we probably want to categorize them first. See #83. Output is provided as json, including the reconized intent and entities and needs to be processed further.
- Models are currently stored under mdr_rasa/models and which model to use is configured via the ros-parameter ~rasa_nlu_model. Is that how it should be?

**Comment by PatrickNa** [comment]
You provide a lot of analysis already - well done! I will catch up with the content and we can discuss this in our next meeting. Until then I'm going to get more familiar with it myself. ☺

**Comment by PatrickNa** [comment]
Regarding you questions:

1. I think the python API is fine. But eventually we should summarize the dependencies in a _requirements.txt_ file (or similar). On a later point we could consider docker. 

2. We should play around with it first. See how it works, how long it takes, how accurate it is etc. We still don't have noise canceling implemented, so my guess is that it will depend on the environmental conditions (e.g. how loud it is in the lab). I don't think categorizing beforehand will make sense, since NLU is just that (and a little more). Don't worry about the _processing part_, yet. This we will address soon. However it is good that you are aware that it is a json message and which data it contains.

3. I have seen your approach and I like it. I would like to hear @alex-mitrevski 's opinion about that.

**Comment by PatrickNa** [comment]
Regarding your code:

In my opinion we don't need a ROS wrapper for a rasa trainer, because there is no need to use ROS for that. I still think it would be nice to have a trainer tool in the repository, but then ROS independent and with the possibility to dynamically pass training-data directory and configuration-file directory.

I like the way you implemented the NLU part. It is well structured and understandable. If there is anything that can be improved, it will be mentioned in the review request. But in principle it seems to do the requested job (I have not tested it yet).

**Comment by argenos** [comment]
> I think the python API is fine. But eventually we should summarize the dependencies in a requirements.txt file (or similar). On a later point we could consider docker.
> 
Much rather manage this through rosdep, docker comes for free in that case (at least with the current config)

**Comment by argenos** [comment]
> In my opinion we don't need a ROS wrapper for a rasa trainer, because there is no need to use ROS for that. I still think it would be nice to have a trainer tool in the repository, but then ROS independent and with the possibility to dynamically pass training-data directory and configuration-file directory.
> 
Agree there, similar case to #71, training and run time in the robot should be separated

**Comment by alex-mitrevski** [comment]
As Patrick said, using the Python API is fine. If the HTTP API is decent, we could eventually consider using Docker, but, in my opinion, it's better to keep the communication overhead to a minimum.

I'll take a look into the code itself and provide comments on it a bit later.

**Comment by argenos** [comment]
> As Patrick said, using the Python API is fine. If the HTTP API is decent, we could eventually consider using Docker, but, in my opinion, it's better to keep the communication overhead to a minimum.
We are not using Docker to run the code in the robot, but all the other dependencies are (or should be) installed through rosdep and checked by Travis using docker.

I don’t want custom installation steps on individual packages. And if it passes the checks, the docker image exists and could be used by whoever does want to use docker.

**Comment by alex-mitrevski** [comment]
We seem to be discussing two different things here. I am only talking about the way in which this ROS wrapper should interact with Rasa, not about the installation procedure of the dependencies.

**Comment by PatrickNa** [comment]
I have tried to run the code on the robot today, but unfortunately a problem appeared. The issue was not your code, but a python conflict.



I will try to run the code on my pc and check whether I can reproduce it or not.

**Pull request merged**
